const CountryList = [ 
  { name: 'Todos', code: '', selected: false }, 
  { name: 'India', code: 'IN', selected: false }, 
  { name: 'Australia', code: 'AU', selected: false }, 
  { name: 'Emiratos Árabes Unidos', code: 'AE', selected: false }, 
  { name: 'Reino Unido', code: 'GB', selected: false }, 
  { name: 'Estados Unidos', code: 'US', selected: false }, 
  { name: 'Francia', code: 'FR', selected: false }, 
  { name: 'Alemania', code: 'DE', selected: false }, 
  { name: 'Japón', code: 'JP', selected: false }, 
  { name: 'Israel', code: 'IL', selected: false },  
  { name: 'Colombia', code: 'CO', selected: false },
  { name: 'México', code: 'MX', selected: false },
  { name: 'Argentina', code: 'AR', selected: false },
  { name: 'Venezuela', code: 'VE', selected: false },
  { name: 'Ecuador', code: 'EC', selected: false },
  { name: 'Chile', code: 'CL', selected: false },
  { name: 'Perú', code: 'PE', selected: false },
  { name: 'Brasil', code: 'BR', selected: false },
  { name: 'Paraguay', code: 'PY', selected: false },
  { name: 'Uruguay', code: 'UY', selected: false },
  { name: 'Bolivia', code: 'BO', selected: false },
  { name: 'Costa Rica', code: 'CR', selected: false },
  { name: 'Panamá', code: 'PA', selected: false },
  { name: 'República Dominicana', code: 'DO', selected: false },
  { name: 'Puerto Rico', code: 'PR', selected: false },
  { name: 'Honduras', code: 'HN', selected: false },
  { name: 'El Salvador', code: 'SV', selected: false },
  { name: 'Guatemala', code: 'GT', selected: false },
  { name: 'Cuba', code: 'CU', selected: false },
  { name: 'Nicaragua', code: 'NI', selected: false }
];

export default CountryList;
